### ISSUE TITLE
unable to handle panic and app get close

### ISSUE THREAD

**Issue by shendkardevesh** [manyuanrong/deno_mongo#63] opened 2020-07-02 03:04 UTC
here is the error details
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: WriteError(WriteError(WriteError { code: 11000, code_name: None, message: "E11000 duplicate key error collection: hops.users index: email_1 dup key: { email: \"test1@gmail.com\" }" })) }', src/command/insert.rs:32:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

and this doesn't get into the catch block, but the app stop its execution.
how can  i handle this panic at deno side.

**Comment by lucacasonato** [comment] 2020-07-09 01:40
You can not at the moment. Duplicate of #53

**Closed** 2020-07-10 02:05 UTC
