### ISSUE TITLE
 Rust panics when I look for an incorrect id

### ISSUE THREAD

**Issue by lupodevelop** [manyuanrong/deno_mongo#89] opened 2020-08-04 08:42 UTC
```
Deno 1.2.0
TypeScript 3.9.6
MongoDriver 0.9.2
```

When I try to use **findOne()** method for searching an incorrect / inexistent ID rust panics and the server crashes. I also try to catch the error, but nothing changes. Is there a way to avoid this tedious problem?

```
    async show ( ctx : any ) {
        try{
        const data = await user.findOne(
            {_id: {$oid: ctx.params.id}},
            );
             ctx.response.body = data;
        } catch (e) {
            ctx.response.status = 404;
            ctx.response.body = {error: "This isn't the user you're looking for"};

        }
    },
```

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromHexError(OddLength)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bson-0.14.1/src/bson.rs:575:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Guillaume-Lebegue** [comment] 2020-08-04 10:00
Duplicate of #86 

If you want a temporary solution, you can cast it to ObjectId. It will throw an error.

   ```
 async show ( ctx : any ) {
        try{
        const id = ObjectId(ctx.params.id);
        const data = await user.findOne(
            {_id: id},
            );
             ctx.response.body = data;
        } catch (e) {
            ctx.response.status = 404;
            ctx.response.body = {error: "This isn't the user you're looking for"};

        }
    },
```

**Comment by lupodevelop** [comment] 2020-08-04 10:50
@Guillaume-Lebegue Thank you. But maybe I forgot to import something, because I can’t find any reference to ObjectId. What did I do wrong? 
It’s my first experiment with Deno + mongo

**Comment by Guillaume-Lebegue** [comment] 2020-08-04 11:42
Ah, yes, you need to import ObjectId from deno_mongo

`import { ObjectId } from 'https://deno.land/x/mongo@v0.9.1/mod.ts';`

**Comment by lupodevelop** [comment] 2020-08-05 06:58
Thank you, so much @Guillaume-Lebegue. I was going to write that it didn't work anyway, but then I realized that I misspelled **ObjectId** :laughing:. I hope this problem of the **findOne()** method will be solved without this workaround through **ObjectId**

**Comment by aps1027** [comment] 2020-08-10 17:55
The following works for me.
```
import { ObjectId } from "https://deno.land/x/mongo@v0.10.1/mod.ts";

static async findById(id: string): Promise<Survey | null> {
    try {
      const survey = await surveyCollection.findOne({
        _id: ObjectId(id),
      });
      return Survey.prepare(survey);
    } catch (e) {
      return null;
    }
  }
```

**Comment by JWebCoder** [comment] 2020-08-13 00:43
> Ah, yes, you need to import ObjectId from deno_mongo
> 
> `import { ObjectId } from 'https://deno.land/x/mongo@v0.9.1/mod.ts';`

Can we have this in the docs?
Thank you.

**Comment by aps1027** [comment] 2020-08-13 14:34
> > Ah, yes, you need to import ObjectId from deno_mongo
> > `import { ObjectId } from 'https://deno.land/x/mongo@v0.9.1/mod.ts';`
> 
> Can we have this in the docs?
> Thank you.

Sure, you can.
If you need more details:
- https://github.com/aps1027/dockerized-deno

**Comment by manyuanrong** [comment] 2020-11-27 05:19
This problem should no longer exist

**Closed by manyuanrong** 2020-11-27 05:19 UTC
